[package]
name = "localos-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
localos-traits = { workspace = true }

tokio       = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
directories = { workspace = true }
mdns-sd     = { workspace = true }
arboard     = { workspace = true }